using System;
using UnityEditor.Experimental.GraphView;
using UnityEngine;

public class SensorSystem : MonoBehaviour
{
    [SerializeField] private float sensorDistance = 9f;
    [SerializeField] private float sensorAngle = 65f;
    [SerializeField] private LayerMask obstaclesMask;
    
    public event Action<Transform> OnPlayerDetected, OnPlayerLost;
    
    private SphereCollider sensorCollider;

    private void Awake()
    {
        sensorCollider = GetComponent<SphereCollider>();
        sensorCollider.radius = sensorDistance;
    }

    private void OnTriggerStay(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            Debug.Log("Player Detectado");

            CheckDetection(other);
        }
    }

    private void CheckDetection(Collider other)
    {
        Vector3 directionToTarget = other.transform.position - transform.position;
        
        //Si hay un obst치culo en medio no es valida la detecci칩n.
        if(Physics.Raycast(transform.position, directionToTarget, sensorDistance, obstaclesMask)) return;
        
        //Revisa el 치ngulo de visi칩n
        if (Vector3.Angle(directionToTarget, transform.forward) < sensorAngle / 2f)
        {
            Debug.Log("Player en rango");
            OnPlayerDetected?.Invoke(other.transform);
        }
        else  OnPlayerLost?.Invoke(other.transform);
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            OnPlayerLost?.Invoke(other.transform);
        }
    }
}
