using System;
using UnityEngine;

public class PlayerInteractionSystem : MonoBehaviour
{
    private IInteractable currentInteractable;
    
    private void OnEnable()
    {
        InputController.Instance.OnInteract += LaunchInteraction;
    }

    private void LaunchInteraction() //Interacci贸n con el objeto actual
    {
        currentInteractable?.Interact(gameObject);
        currentInteractable?.OnInteractableDeactivated();
        currentInteractable = null;
    }

    private void OnTriggerEnter(Collider other) //Actualizaci贸n del interactuador actual.
    {
        Debug.Log("Encontr贸 interactuable: ");
        if (other.TryGetComponent(out IInteractable interactable))
        {
            Debug.Log("Encontr贸 interactuable: " + interactable);
            if (interactable != currentInteractable)
            {
                currentInteractable?.OnInteractableDeactivated();
            }
            
            currentInteractable = interactable;
            currentInteractable?.OnInteractableActivated();
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.TryGetComponent(out IInteractable interactable)) 
        {
            interactable.OnInteractableDeactivated();

            if (interactable == currentInteractable)
            {
                currentInteractable = null;
            }
        }
    }
}
